<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="OmniSharp.Extensions.LanguageServer" Version="0.19.9" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\XamlTolerantParser\XamlTolerantParser.csproj" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="XamlLanguageServerTests" />
	</ItemGroup>
</Project>
